### ISSUE TITLE
Build the HTML structure

### ISSUE THREAD

**Issue by flokamp** [JPKashlak/who-you-gonna-call#1]
### Elements to include:

1. Page title
2. Search field
3. Covid card
-- Title
-- Numbers
-- Active cases
-- Recovered
-- Deaths
4. Rep card
-- Name
-- Role
-- Twitter
-- Facebook

**Comment by JPKashlak** [comment]
Laid the general groundwork for the html & css. 
Still need to work on some finer details and responsiveness.
